using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Sirenix.OdinInspector;
using UnityEditor.Experimental.GraphView;
using UnityEngine;
using UnityEngine.Tilemaps;
using UnityEngine.WSA;
using Random = UnityEngine.Random;

public class TileMapGameObjectController : MonoBehaviour
{
    [Header("ï¿½ï¿½Æ¬")]
    public Tilemap tilemap; // ï¿½ï¿½Òªï¿½Ö¶ï¿½ï¿½ï¿½Tilemapï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×§ï¿½ï¿½ï¿½ï¿½ï¿½Ö¶ï¿½
    public Sprite[] TileSprites; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Tileï¿½ï¿½GameObjectÔ¤ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ï¿½
    public GameObject TilePrefab;
    public Dictionary<Vector2, GameObject> TileMapData = new Dictionary<Vector2, GameObject>();
    public HashSet<Vector2Int> occupiedTiles = new HashSet<Vector2Int>();


    private List<GameObject> generatedObjects = new List<GameObject>(); // ï¿½æ´¢ï¿½ï¿½ï¿½Éµï¿½GameObject

    public Transform gridParentTransf; //
    [Header("Ð¡ï¿½ï¿½ï¿½ï¿½")]
    public GameObject[] smallObjectsPrefabsLevel1;
    public GameObject[] smallObjectLevel2;
    public GameObject[] smallObjectLevel3; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ð¡ï¿½ï¿½ï¿½ï¿½ï¿½Ô¤ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ï¿½

    public float smallObjectProbability = 0.2f; // Ð¡ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉµÄ¸ï¿½ï¿½ï¿½

    public Vector2Int FilpStartPos;
    [FoldoutGroup("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")]
    public float noiseScale1 = 0.1f; // ï¿½ï¿½ï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [FoldoutGroup("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")]
    public float noiseScale2 = 0.05f; // ï¿½ï¿½ï¿½ï¿½2ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    [FoldoutGroup("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")]
    public float noiseWeight1 = 0.5f; // ï¿½ï¿½ï¿½ï¿½1ï¿½ï¿½È¨ï¿½ï¿½
    [FoldoutGroup("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½")]
    public float noiseWeight2 = 0.5f; // ï¿½ï¿½ï¿½ï¿½2ï¿½ï¿½È¨ï¿½ï¿½

    private Vector2 randomOffset1;
    private Vector2 randomOffset2;


    public static int CurLevel = 1;
    public static bool isLoadLevel = false;

    [Header("Ê³ï¿½ï¿½")]
    public GameObject[] foodPrefabs; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê³ï¿½ï¿½ï¿½Ô¤ï¿½Æ¼ï¿½ï¿½ï¿½ï¿½ï¿½
    public List<GameObject> foodObjects = new List<GameObject>(); // ï¿½æ´¢ï¿½ï¿½ï¿½Éµï¿½Ê³ï¿½ï¿½ï¿½ï¿½ï¿½
    public float foodGenerationProbability = 0.1f; // Ê³ï¿½ï¿½ï¿½ï¿½ï¿½É¸ï¿½ï¿½ï¿½
    private List<GameObject> currentFoods = new List<GameObject>(); // ï¿½ï¿½Ç°ï¿½ï¿½ï¿½Éµï¿½Ê³ï¿½ï¿½ï¿½Ð±ï¿½
    public float foodGenerationInterval = 10.0f; // Ê³ï¿½ï¿½ï¿½ï¿½ï¿½É¼ï¿½ï¿½
    void Start()
    {
        InstorageTileMapData();
        GenerateFood();
        StartCoroutine(GenerateFoodPeriodically());
    }
    IEnumerator GenerateFoodPeriodically()
    {
        while (true)
        {
            yield return new WaitForSeconds(foodGenerationInterval);
            GenerateFood();
        }
    }
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.RightShift))
        {
            FilpAllTile(FilpStartPos);
        }
    }
    void GenerateFood()
    {
        if (currentFoods.Count >= 2) return;

        foreach (Transform _gridTransf in gridParentTransf)
        {
            Vector2Int gridPos = new Vector2Int(
                Mathf.FloorToInt(_gridTransf.position.x),
                Mathf.FloorToInt(_gridTransf.position.y)
            );

            if (occupiedTiles.Contains(gridPos)) continue;

            if (Random.value < foodGenerationProbability)
            {
                int foodIndex = Random.Range(0, foodPrefabs.Length);
                GameObject foodPrefab = foodPrefabs[foodIndex];

                Vector3 foodLocalPosition = new Vector3(Random.Range(-0.05f, 0.05f), Random.Range(-0.05f, 0.05f), 0);
                GameObject foodObject = Instantiate(foodPrefab, Vector3.zero, Quaternion.identity, _gridTransf);
                foodObject.transform.localPosition = foodLocalPosition;
                foodObject.transform.SetParent(_gridTransf.Find("Sprite"));
                foodObjects.Add(foodObject);
                _gridTransf.GetComponent<GridSingle>().food=foodObject;


                // ï¿½ï¿½ï¿½ï¿½Ê³ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                Food foodComponent = foodObject.GetComponent<Food>();
                foodComponent.foodType = (FoodType)foodIndex;
                // ï¿½ï¿½ï¿½Óµï¿½ï¿½ï¿½Õ¼ï¿½Ã¸ï¿½ï¿½Ó¼ï¿½ï¿½ï¿½ï¿½ï¿½
                occupiedTiles.Add(gridPos);

                // ï¿½ï¿½ï¿½Óµï¿½ï¿½ï¿½Ç°ï¿½ï¿½ï¿½Éµï¿½Ê³ï¿½ï¿½ï¿½Ð±ï¿½
                currentFoods.Add(foodObject);


                break; // ï¿½ï¿½ï¿½ï¿½Ò»ï¿½ï¿½Ê³ï¿½ï¿½ï¿½ï¿½Ë³ï¿½Ñ­ï¿½ï¿½
            }
        }
    }
    /// <summary>
    /// ï¿½ï¿½Òªï¿½ï¿½ï¿½ß³Ô¶ï¿½ï¿½Óµï¿½Ê±ï¿½ò±»µï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="gridPos"></param>
    public void RemoveFood(Vector2Int gridPos)
    {
        GridSingle _grid=GetTileObject(gridPos).GetComponent<GridSingle>();
        if (occupiedTiles.Contains(gridPos))
        {
            occupiedTiles.Remove(gridPos);
        }
        GameObject foodObject=_grid.food;
        if (currentFoods.Contains(foodObject))
        {
            currentFoods.Remove(foodObject);
        }
        Destroy(foodObject);
        _grid.food=null;
        GenerateFood();
    }




    #region Tileï¿½ï¿½ï¿½ï¿½
    void InstorageTileMapData()
    {
        foreach (Transform _gridTransf in gridParentTransf)
        {
            string[] _indexs = _gridTransf.name.Split("_");
            int _index1 = int.Parse(_indexs[1]);
            int _index2 = int.Parse(_indexs[2]);
            TileMapData[new Vector2(_index1, _index2)] = _gridTransf.gameObject;
        }
    }
    /// <summary>
    /// ï¿½ï¿½ï¿½Ý¶ï¿½Î¬ï¿½ï¿½ï¿½ï¿½ï¿½È¡ï¿½ï¿½Ó¦ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="_pos"></param>
    /// <returns></returns>
    public GameObject GetTileObject(Vector2Int _pos)
    {
        if (TileMapData.ContainsKey(_pos))
        {
            return TileMapData[_pos];
        }

        return null;
    }
    #endregion

    #region ï¿½ï¿½ï¿½ï¿½ï¿½Ð»ï¿½
    public void FilpAllTile(Vector2Int _startPos)
    {
        StartCoroutine(FilpAllTileIEnum(_startPos));
    }
    public float flipTimeSplit = 0.5f;
    
    // ï¿½ï¿½ï¿½Ïµï¿½ï¿½Â·ï¿½×ªï¿½ï¿½Í¼  4-- -6
    //IEnumerator FilpFromUpToBottom()
    //{
    //    Dictionary<int, List<Animator>> animDic = new Dictionary<int, List<Animator>>();
    //    foreach (Transform _gridTransf in gridParentTransf)
    //    {
    //        int _index = int.Parse(_gridTransf.name.Split("_")[1]);
    //        if (!animDic.ContainsKey(_index))
    //        {
    //            animDic[_index] = new List<Animator>();
    //        }
    //        animDic[_index].Add(_gridTransf.GetComponent<Animator>());
    //    }
    //    for (int i = 4; i >= -6; i--)
    //    {
    //        List<Animator> _animList = animDic[i];
    //        foreach (var _anim in _animList)
    //        {
    //            _anim.Play("Grid_Filp1");
    //        }
    //        yield return new WaitForSeconds(flipTimeSplit);
    //    }
    //}


    IEnumerator FilpAllTileIEnum(Vector2Int _startPos)
    {
        isLoadLevel = true;

        List<Vector2Int> flipedSprite = new List<Vector2Int>();
        //Ò»ï¿½ï¿½
        List<Vector2Int> _stack = new List<Vector2Int> { _startPos };
        while (_stack.Count > 0)
        {
            List<Vector2Int> _tempStack = new List<Vector2Int>();
            foreach (var _vector2 in _stack)
            {
                if (TileMapData.ContainsKey(_vector2))
                {
                    flipedSprite.Add(_vector2);
                    //ï¿½Ð¸ï¿½ï¿½ï¿½ï¿½Ý²ï¿½ï¿½Ò»ï¿½Î´ï¿½ï¿½×ªï¿½ï¿½
                    TileMapData[_vector2].GetComponent<Animator>().Play("Grid_Filp1");

                    var _aroundGrids = GridManager.getAroundGrids(_vector2);
                    foreach (var _aroundGrid in _aroundGrids)
                    {
                        if (TileMapData.ContainsKey(_aroundGrid) && !flipedSprite.Contains(_aroundGrid))
                        {
                            _tempStack.Add(_aroundGrid);
                        }
                    }
                }
            }
            _stack = _tempStack;
          
            
            yield return new WaitForSeconds(flipTimeSplit);
        }

        CurLevel++;
        isLoadLevel = false;

        //todo: ï¿½Ø¿ï¿½ï¿½ï¿½ï¿½Ø½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ò½ï¿½ï¿½ï¿½
    }
    #endregion

    #region ï¿½Ø¿ï¿½ï¿½ï¿½ï¿½ï¿½
    [Button("ï¿½ï¿½Ê¼ï¿½ï¿½Grid")]
    public void InitGenerateGridGO()
    {
        ClearGeneratedObjects();
        GenerateOffsetsAndNoise();
        GenerateGameObjectsFromTiles();

        // ï¿½ï¿½ï¿½ï¿½ï¿½Õ¼ï¿½Ã¸ï¿½ï¿½Ó¼ï¿½ï¿½ï¿½
        occupiedTiles.Clear();
        GenerateFood();
    }

    private string spriteName = "Sprite";
    [Button("ï¿½ï¿½È¡ï¿½ï¿½Í¼ï¿½ï¿½ï¿½ï¿½")]
    public void LoadGridData()
    {
        Transform level1Transf = GameObject.Find("Level1").transform;
        Transform level2Transf = GameObject.Find("Level2").transform;
        Transform level3Transf = GameObject.Find("Level3").transform;

        foreach (Transform _transf in gridParentTransf)
        {
            string _name = _transf.name;
            _transf.Find("Sprite").GetComponent<SpriteRenderer>().sprite = level1Transf.Find(_name).GetComponent<SpriteRenderer>().sprite;
            _transf.GetComponentInChildren<GridAnimEvent>().level1TargetSprite = level2Transf.Find(_name).GetComponent<SpriteRenderer>().sprite;
            _transf.GetComponentInChildren<GridAnimEvent>().level2TargetSprite = level3Transf.Find(_name).GetComponent<SpriteRenderer>().sprite;

            Transform _transfChild = _transf.Find(spriteName);
            for(int i = _transfChild.childCount-1;i>=0;i--)
            {
                DestroyImmediate(_transfChild.GetChild(i).gameObject);
            }
            // var _smallGo = _transf.Find(smallObjectName);
            // if (_smallGo != null)
            // {
            //     DestroyImmediate(_smallGo.gameObject);
            // }

            GameObject[] _smallGoPrefabs = null;
            if(CurLevel == 1)
            {
                _smallGoPrefabs = smallObjectsPrefabsLevel1;
            }
            else if(CurLevel == 2)
            {
                _smallGoPrefabs = smallObjectLevel2;
            }
            else if(CurLevel == 3)
            {
                _smallGoPrefabs = smallObjectLevel3;
            }
<<<<<<< HEAD
            //Debug.Log($"{CurLevel}  {_smallGoPrefabs.Length}");
            //´¦ÀíÐ¡ÎïÌå
=======
            
            //ï¿½ï¿½ï¿½ï¿½Ð¡ï¿½ï¿½ï¿½ï¿½
>>>>>>> origin/master
            if (Random.value < smallObjectProbability)
            {
                int smallObjectIndex = Random.Range(0, _smallGoPrefabs.Length);
                GameObject smallObjectPrefab = _smallGoPrefabs[smallObjectIndex];

                Vector3 ObjectLocalPosition = new Vector3(Random.Range(-0.25f, 0.25f), Random.Range(-0.25f, 0.25f), 0);
                GameObject smallObject = Instantiate(smallObjectPrefab, Vector3.zero,Quaternion.identity, _transf);
                smallObject.transform.localPosition = ObjectLocalPosition;
                smallObject.transform.SetParent(_transf.Find("Sprite"));
                //smallObject.name = "SmallObject_" + localPlace.x + "_" + localPlace.y;
                smallObject.name = smallObjectName;
            }
        }
    }

    void GenerateOffsetsAndNoise()
    {
        // ï¿½ï¿½Ê¼ï¿½ï¿½ï¿½ï¿½ï¿½Æ«ï¿½ï¿½
        randomOffset1 = new Vector2(Random.Range(0f, 1000f), Random.Range(0f, 1000f));
        randomOffset2 = new Vector2(Random.Range(0f, 1000f), Random.Range(0f, 1000f));

        // ï¿½ï¿½Ì¬ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ó±ä»¯
        noiseScale1 = Random.Range(0.01f, 0.2f);
        noiseScale2 = Random.Range(0.01f, 0.2f);
        noiseWeight1 = Random.Range(0.3f, 0.7f);
        noiseWeight2 = 1 - noiseWeight1;
    }

    void GenerateGameObjectsFromTiles()
    {
        BoundsInt bounds = tilemap.cellBounds;
        TileBase[] allTiles = tilemap.GetTilesBlock(bounds);

        for (int x = 0; x < bounds.size.x; x++)
        {
            for (int y = 0; y < bounds.size.y; y++)
            {
                TileBase tile = allTiles[x + y * bounds.size.x];
                if (tile != null)
                {
                    Vector3Int localPlace = new Vector3Int(x + bounds.xMin, y + bounds.yMin, 0);
                    Vector3 place = tilemap.CellToWorld(localPlace);

                    // Ê¹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Perlinï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É´ï¿½ï¿½Ð¸ï¿½ï¿½ï¿½ä»¯ï¿½Äµï¿½ï¿½Î£ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ«ï¿½ï¿½
                    float noiseValue1 = Mathf.PerlinNoise((x + randomOffset1.x) * noiseScale1, (y + randomOffset1.y) * noiseScale1);
                    float noiseValue2 = Mathf.PerlinNoise((x + randomOffset2.x) * noiseScale2, (y + randomOffset2.y) * noiseScale2);
                    float combinedNoiseValue = noiseValue1 * noiseWeight1 + noiseValue2 * noiseWeight2;

                    int prefabIndex = Mathf.FloorToInt(combinedNoiseValue * TileSprites.Length);
                    if (prefabIndex >= TileSprites.Length)
                    {
                        prefabIndex = TileSprites.Length - 1;
                    }

                    GameObject tileGO = Instantiate(TilePrefab, place, Quaternion.identity, gridParentTransf);
                    tileGO.GetComponent<GridSingle>().Init(TileSprites[prefabIndex]);
                    tileGO.name = "Tile_" + localPlace.x + "_" + localPlace.y;

                    generatedObjects.Add(tileGO); // ï¿½ï¿½ï¿½ï¿½ï¿½Éµï¿½GameObjectï¿½ï¿½ï¿½Óµï¿½ï¿½Ð±ï¿½ï¿½ï¿½
                }
            }
        }
    }
    
    string smallObjectName = "SmallObject";
    public void ReGenerateSmallGameObject(Transform _transf)
    {
        //ï¿½ï¿½ï¿½ï¿½Éµï¿½Ð¡ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Transform _transfChild = _transf.Find(spriteName);
        for(int i = _transfChild.childCount-1;i>=0;i--)
        {
            Destroy(_transfChild.GetChild(i).gameObject);
        }
<<<<<<< HEAD


        GameObject[] _smallGoPrefabs = null;
        if (CurLevel == 1)
        {
            _smallGoPrefabs = smallObjectsPrefabsLevel1;
        }
        else if (CurLevel == 2)
        {
            _smallGoPrefabs = smallObjectLevel2;
        }
        else if (CurLevel == 3)
        {
            _smallGoPrefabs = smallObjectLevel3;
        }
        //Éú³ÉÐÂµÄÐ¡ÎïÌå
=======
        
        
        //ï¿½ï¿½ï¿½ï¿½ï¿½Âµï¿½Ð¡ï¿½ï¿½ï¿½ï¿½
>>>>>>> origin/master
        if (Random.value < smallObjectProbability)
        {
            int smallObjectIndex = Random.Range(0, _smallGoPrefabs.Length);
            GameObject smallObjectPrefab = _smallGoPrefabs[smallObjectIndex];

            Vector3 ObjectLocalPosition = new Vector3(Random.Range(-0.25f, 0.25f), Random.Range(-0.25f, 0.25f), 0);
            GameObject smallObject = Instantiate(smallObjectPrefab, Vector3.zero, Quaternion.identity, _transf);
            smallObject.transform.localPosition = ObjectLocalPosition;
            smallObject.transform.SetParent(_transf.Find("Sprite")); 
            smallObject.transform.localRotation = Quaternion.identity;
            smallObject.name = smallObjectName;
        }

        //if (Random.value < smallObjectProbability)
        //{
        //    int smallObjectIndex = Random.Range(0, smallObjectsPrefabsLevel1.Length);
        //    GameObject smallObjectPrefab = smallObjectsPrefabsLevel1[smallObjectIndex];
        //    Vector3 smallObjectLocalPosition = new Vector3(Random.Range(-0.25f, 0.25f), Random.Range(-0.25f, 0.25f), 0);
        //    GameObject smallObject = Instantiate(smallObjectPrefab,Vector3.zero , Quaternion.identity, _transf);
        //    smallObject.transform.localPosition = smallObjectLocalPosition;
        //    smallObject.transform.SetParent(_transf.Find("Sprite"));
        //    smallObject.transform.localRotation = Quaternion.identity;
        //    //smallObject.name = "SmallObject_" + localPlace.x + "_" + localPlace.y;
        //}
    }

    void ClearGeneratedObjects()
    {
        for (int i = gridParentTransf.childCount - 1; i >= 0; i--)
        {
            DestroyImmediate(gridParentTransf.GetChild(i).gameObject);
        }

        generatedObjects.Clear(); // ï¿½ï¿½ï¿½ï¿½Ð±ï¿½
    }
    #endregion
}
